export const contactTypes = {
	// Sync
	GET_CONTACTS_REQUEST: 'contact|GET_CONTACTS_REQUEST',
	GET_CONTACTS_SUCCESS: 'contact|GET_CONTACTS_SUCCESS',
	GET_CONTACTS_FAILED: 'contact|GET_CONTACTS_FAILED',
	SET_COORDINATES_SUCCESS: 'contact|SET_COORDINATES_SUCCESS',

	// Async
	GET_CONTACTS_ASYNC: 'contact|GET_CONTACTS_ASYNC',
	SET_COORDINATES_ASYNC: 'contact|SET_COORDINATES_ASYNC',
}
